version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: golang:1.15.12-stretch
    steps:
      - checkout
      - run:
          name: lint-dockerfile
          command: |
            curl -ssl -o /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile
      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: |
            chmod +x build_push_image_karsajobs.sh
            sh build_push_image_karsajobs.sh
workflows:
  version: 2
  build:
    jobs:
      - build