version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run:
          name: lint-dockerfile
          command: |
            curl -ssl https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
  deploy:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run:
          name: build-app-karsajobs
          command: sh build_push_image_karsajobs.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint